### ISSUE TITLE
Error with custom installation on windows

### ISSUE THREAD

**Issue by patrickmorel** [maximedaraize/create-scss-cli#8]
**Describe the bug**
Selecting the **custom** options in create-scss-cli does 
not delete selected directory and does not update "@import" in main.scss

**To Reproduce**
see file: 
 [message.txt](https://github.com/maximedaraize/create-scss-cli/files/7199257/message.txt)
 
 ### Error message

```sh
(node:8748) UnhandledPromiseRejectionWarning: TypeError: fs.rm is not a function
    at C:\Users\pmore\AppData\Roaming\npm\node_modules\create-scss-cli\src\index.js:70:16
    at Array.forEach (<anonymous>)
    at copyFiles (C:\Users\pmore\AppData\Roaming\npm\node_modules\create-scss-cli\src\index.js:69:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:8748) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8748) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Expected behavior**
Selected files should be removed or emptied

**Additional context**
- OS: Windows 10 Home 10.0.19043 Build 19043 
- Node: ? 
- Terminal:  PowerShell

**Comment by maximedaraize** [comment]
# Node.js related
The bug is related to Node.js versions under 14.0.0.

I was able to reproduce this issue when using Node.js 11, 12, or 13.

## Solution

Install the **latest** version of node.js or the recommended version (**14.17.6**)

[nodejs.org](https://nodejs.org/en/)
